server:
  host: 0.0.0.0
  port: 5002
  debug: false
logging:
  level: WARNING
pipeline:
  maas:
    enabled: false
  ocr_api:
    api_host: host.docker.internal
    api_port: 8080
    connect_timeout: 30
    request_timeout: 300
  layout:
    device: cpu
  result_formatter:
    output_format: both
